# Generated by Django 5.2.8 on 2025-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_adminlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
