# Generated by Django 5.2.8 on 2025-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_adminlog_user_adminlog_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
